CREATE OR ALTER PROCEDURE [site].[proc_AddOrUpdateSiteCollection]
    @json nvarchar(max)
AS
BEGIN

    DECLARE @timestamp datetime2(7) = GETUTCDATE()

    ;WITH sites AS
        (
            SELECT
                AllowDownloadingNonWebViewableFiles,
                AllowEditing,
                AnonymousLinkExpirationInDays,
                AuthenticationContextLimitedAccess,
                AuthenticationContextName,
                BlockDownloadLinksFileType,
                BlockDownloadPolicy,
                BlockGuestsAsSiteAdmin,
                CommentsOnSitePagesDisabled,
                CompatibilityLevel,
                ConditionalAccessPolicy,
                CreatedDate,
                DefaultLinkPermission,
                DefaultLinkToExistingAccess,
                DefaultLinkToExistingAccessReset,
                DefaultShareLinkRole,
                DefaultShareLinkScope,
                DefaultSharingLinkType,
                DeletedDate,
                DenyAddAndCustomizePages,
                [Description],
                DisableAppViews,
                DisableCompanyWideSharingLinks,
                DisableFlows,
                ExcludeBlockDownloadPolicySiteOwners,
                ExternalUserExpirationInDays,
                Geolocation,
                GroupId = ISNULL(GroupId, '00000000-0000-0000-0000-000000000000'),
                HasHolds,
                HubSiteId = ISNULL(HubSiteId, '00000000-0000-0000-0000-000000000000'),
                IBMode = site.InformationBarrierMode.Id,
                IsHubSite,
                IsTeamsChannelConnected,
                IsTeamsConnected,
                LastContentModifiedDate,
                Lcid,
                LimitedAccessFileType,
                ListsShowHeaderAndNavigation,
                LockIssue,
                LockState = site.LockState.Id,
                LoopDefaultSharingLinkRole,
                LoopDefaultSharingLinkScope,
                LoopOverrideSharingCapability,
                LoopSharingCapability,
                MediaTranscription,
                OverrideBlockUserInfoVisibility,
                OverrideSharingCapability,
                OverrideTenantAnonymousLinkExpirationPolicy,
                OverrideTenantExternalUserExpirationPolicy,
                [Owner] = COALESCE(upan.ObjectId,upam.ObjectId,'00000000-0000-0000-0000-000000000000'),
                PWAEnabled,
                ReadOnlyAccessPolicy,
                ReadOnlyForBlockDownloadPolicy,
                ReadOnlyForUnmanagedDevices,
                RelatedGroupId = ISNULL(RelatedGroupId, '00000000-0000-0000-0000-000000000000'),
                RequestFilesLinkEnabled,
                RequestFilesLinkExpirationInDays,
                RestrictedAccessControl,
                RestrictedToRegion,
                SensitivityLabel = ISNULL(SensitivityLabel, '00000000-0000-0000-0000-000000000000'),
                SharingAllowedDomainList,
                SharingBlockedDomainList,
                SharingCapability,
                SharingDomainRestrictionMode,
                SharingLockDownCanBeCleared,
                SharingLockDownEnabled,
                ShowPeoplePickerSuggestionsForGuestUsers,
                SiteCreationSource = ISNULL(SiteCreationSource, '00000000-0000-0000-0000-000000000000'),
                SiteDefinedSharingCapability,
                SiteId,
                SiteUrl,
                SocialBarOnSitePagesDisabled,
                [Status],
                StorageMaximumLevel,
                StorageQuotaType,
                StorageUsage,
                StorageWarningLevel,
                TeamsChannelType = TeamsChannelType,
                Template,
                TimeZoneId,
                Title,
                TotalFileCount,
                WebsCount,
                RowCreated = @timestamp,
                RowUpdated = @timestamp
            FROM
                OPENJSON (@json, N'lax $') WITH 
                (
                    AllowDownloadingNonWebViewableFiles            bit,
                    AllowEditing                                   bit,
                    AnonymousLinkExpirationInDays                  int,
                    AuthenticationContextLimitedAccess             bit,
                    AuthenticationContextName                      nvarchar(255),
                    BlockDownloadLinksFileType                     int,
                    BlockDownloadPolicy                            bit,
                    BlockGuestsAsSiteAdmin                         int,
                    CommentsOnSitePagesDisabled                    bit,
                    CompatibilityLevel                             int,
                    ConditionalAccessPolicy                        int,
                    CreatedDate                                    datetime2(7),
                    DefaultLinkPermission                          int,
                    DefaultLinkToExistingAccess                    bit,
                    DefaultLinkToExistingAccessReset               bit,
                    DefaultShareLinkRole                           int,
                    DefaultShareLinkScope                          int,
                    DefaultSharingLinkType                         int,
                    DeletedDate                                    datetime2(7),
                    DenyAddAndCustomizePages                       bit,
                    [Description]                                  nvarchar(500)    N'$.Description',
                    DisableAppViews                                int,
                    DisableCompanyWideSharingLinks                 bit,
                    DisableFlows                                   bit,
                    ExcludeBlockDownloadPolicySiteOwners           bit,
                    ExternalUserExpirationInDays                   int,
                    Geolocation                                    nvarchar(10),
                    GroupId                                        uniqueidentifier,
                    HasHolds                                       bit,
                    HubSiteId                                      uniqueidentifier,
                    IBMode                                         nvarchar(100),
                    IsHubSite                                      bit,
                    IsTeamsChannelConnected                        bit,
                    IsTeamsConnected                               bit,
                    LastContentModifiedDate                        datetime2(7),
                    Lcid                                           int,
                    LimitedAccessFileType                          int,
                    ListsShowHeaderAndNavigation                   bit,
                    LockIssue                                      nvarchar(450),
                    LockState                                      nvarchar(100),
                    LoopDefaultSharingLinkRole                     int,
                    LoopDefaultSharingLinkScope                    int,
                    LoopOverrideSharingCapability                  bit,
                    LoopSharingCapability                          int,
                    MediaTranscription                             int,
                    OverrideBlockUserInfoVisibility                int,
                    OverrideSharingCapability                      bit,
                    OverrideTenantAnonymousLinkExpirationPolicy    bit,
                    OverrideTenantExternalUserExpirationPolicy     bit,
                    [Owner]                                        nvarchar(256),
                    PWAEnabled                                     int,
                    ReadOnlyAccessPolicy                           bit,
                    ReadOnlyForBlockDownloadPolicy                 bit,
                    ReadOnlyForUnmanagedDevices                    bit,
                    RelatedGroupId                                 uniqueidentifier,
                    RequestFilesLinkEnabled                        bit,
                    RequestFilesLinkExpirationInDays               int,
                    RestrictedAccessControl                        bit,
                    RestrictedToRegion                             int,
                    SensitivityLabel                               uniqueidentifier,
                    SharingAllowedDomainList                       nvarchar(max),
                    SharingBlockedDomainList                       nvarchar(max),
                    SharingCapability                              int,
                    SharingDomainRestrictionMode                   int,
                    SharingLockDownCanBeCleared                    bit,
                    SharingLockDownEnabled                         bit,
                    ShowPeoplePickerSuggestionsForGuestUsers       bit,
                    SiteCreationSource                             uniqueidentifier,
                    SiteDefinedSharingCapability                   int,
                    SiteId                                         uniqueidentifier,
                    SiteUrl                                        nvarchar(450),
                    SocialBarOnSitePagesDisabled                   bit,
                    [Status]                                       nvarchar(255),
                    StorageMaximumLevel                            bigint,
                    StorageQuotaType                               nvarchar(255),
                    StorageUsage                                   bigint,
                    StorageWarningLevel                            bigint,
                    TeamsChannelType                               int,
                    Template                                       nvarchar(255),
                    TimeZoneId                                     int,
                    Title                                          nvarchar(255),
                    TotalFileCount                                 int,
                    WebsCount                                      int
                ) js
                LEFT JOIN
                site.InformationBarrierMode ON js.IBMode = site.InformationBarrierMode.InformationBarrierMode
                LEFT JOIN
                site.LockState ON js.LockState = site.LockState.LockState
                LEFT JOIN
                principal.UserPrincipalActive upan ON js.Owner = upan.UserPrincipalName
                LEFT JOIN
                principal.UserPrincipalActive upam ON js.Owner = upam.Mail
        )
   
    MERGE INTO site.SiteCollection AS Existing
    USING sites AS New
    ON New.SiteId = Existing.SiteId
    WHEN MATCHED THEN
        UPDATE SET
            Existing.[Description]                                  = ISNULL( New.[Description],                                  Existing.[Description] ),
            Existing.DisableAppViews                                = ISNULL( New.DisableAppViews,                                Existing.DisableAppViews ),
            Existing.[Status]                                       = ISNULL( New.[Status],                                       Existing.[Status] ),
            Existing.AllowDownloadingNonWebViewableFiles            = ISNULL( New.AllowDownloadingNonWebViewableFiles,            Existing.AllowDownloadingNonWebViewableFiles ),
            Existing.AllowEditing                                   = ISNULL( New.AllowEditing,                                   Existing.AllowEditing ),
            Existing.AnonymousLinkExpirationInDays                  = ISNULL( New.AnonymousLinkExpirationInDays,                  Existing.AnonymousLinkExpirationInDays ),
            Existing.AuthenticationContextLimitedAccess             = ISNULL( New.AuthenticationContextLimitedAccess,             Existing.AuthenticationContextLimitedAccess ),
            Existing.AuthenticationContextName                      = ISNULL( New.AuthenticationContextName,                      Existing.AuthenticationContextName ),
            Existing.BlockDownloadLinksFileType                     = ISNULL( New.BlockDownloadLinksFileType,                     Existing.BlockDownloadLinksFileType ),
            Existing.BlockDownloadPolicy                            = ISNULL( New.BlockDownloadPolicy,                            Existing.BlockDownloadPolicy ),
            Existing.BlockGuestsAsSiteAdmin                         = ISNULL( New.BlockGuestsAsSiteAdmin,                         Existing.BlockGuestsAsSiteAdmin ),
            Existing.CommentsOnSitePagesDisabled                    = ISNULL( New.CommentsOnSitePagesDisabled,                    Existing.CommentsOnSitePagesDisabled ),
            Existing.CompatibilityLevel                             = ISNULL( New.CompatibilityLevel,                             Existing.CompatibilityLevel ),
            Existing.ConditionalAccessPolicy                        = ISNULL( New.ConditionalAccessPolicy,                        Existing.ConditionalAccessPolicy ),
            Existing.CreatedDate                                    = ISNULL( New.CreatedDate,                                    Existing.CreatedDate ),
            Existing.DefaultLinkPermission                          = ISNULL( New.DefaultLinkPermission,                          Existing.DefaultLinkPermission ),
            Existing.DefaultLinkToExistingAccess                    = ISNULL( New.DefaultLinkToExistingAccess,                    Existing.DefaultLinkToExistingAccess ),
            Existing.DefaultLinkToExistingAccessReset               = ISNULL( New.DefaultLinkToExistingAccessReset,               Existing.DefaultLinkToExistingAccessReset ),
            Existing.DefaultShareLinkRole                           = ISNULL( New.DefaultShareLinkRole,                           Existing.DefaultShareLinkRole ),
            Existing.DefaultShareLinkScope                          = ISNULL( New.DefaultShareLinkScope,                          Existing.DefaultShareLinkScope ),
            Existing.DefaultSharingLinkType                         = ISNULL( New.DefaultSharingLinkType,                         Existing.DefaultSharingLinkType ),
            Existing.DeletedDate                                    = New.DeletedDate,
            Existing.DenyAddAndCustomizePages                       = ISNULL( New.DenyAddAndCustomizePages,                       Existing.DenyAddAndCustomizePages ),
            Existing.DisableCompanyWideSharingLinks                 = ISNULL( New.DisableCompanyWideSharingLinks,                 Existing.DisableCompanyWideSharingLinks ),
            Existing.DisableFlows                                   = ISNULL( New.DisableFlows,                                   Existing.DisableFlows ),
            Existing.ExcludeBlockDownloadPolicySiteOwners           = ISNULL( New.ExcludeBlockDownloadPolicySiteOwners,           Existing.ExcludeBlockDownloadPolicySiteOwners ),
            Existing.ExternalUserExpirationInDays                   = ISNULL( New.ExternalUserExpirationInDays,                   Existing.ExternalUserExpirationInDays ),
            Existing.Geolocation                                    = ISNULL( New.Geolocation,                                    Existing.Geolocation ),
            Existing.GroupId                                        = ISNULL( New.GroupId,                                        Existing.GroupId ),
            Existing.HasHolds                                       = ISNULL( New.HasHolds,                                       Existing.HasHolds ),
            Existing.HubSiteId                                      = ISNULL( New.HubSiteId,                                      Existing.HubSiteId ),
            Existing.IBMode                                         = ISNULL( New.IBMode,                                         Existing.IBMode ),
            Existing.IsHubSite                                      = ISNULL( New.IsHubSite,                                      Existing.IsHubSite ),
            Existing.IsTeamsChannelConnected                        = ISNULL( New.IsTeamsChannelConnected,                        Existing.IsTeamsChannelConnected ),
            Existing.IsTeamsConnected                               = ISNULL( New.IsTeamsConnected,                               Existing.IsTeamsConnected ),
            Existing.LastContentModifiedDate                        = ISNULL( New.LastContentModifiedDate,                        Existing.LastContentModifiedDate ),
            Existing.Lcid                                           = ISNULL( New.Lcid,                                           Existing.Lcid ),
            Existing.LimitedAccessFileType                          = ISNULL( New.LimitedAccessFileType,                          Existing.LimitedAccessFileType ),
            Existing.ListsShowHeaderAndNavigation                   = ISNULL( New.ListsShowHeaderAndNavigation,                   Existing.ListsShowHeaderAndNavigation ),
            Existing.LockIssue                                      = ISNULL( New.LockIssue,                                      Existing.LockIssue ),
            Existing.LockState                                      = ISNULL( New.LockState,                                      Existing.LockState ),
            Existing.LoopDefaultSharingLinkRole                     = ISNULL( New.LoopDefaultSharingLinkRole,                     Existing.LoopDefaultSharingLinkRole ),
            Existing.LoopDefaultSharingLinkScope                    = ISNULL( New.LoopDefaultSharingLinkScope,                    Existing.LoopDefaultSharingLinkScope ),
            Existing.LoopOverrideSharingCapability                  = ISNULL( New.LoopOverrideSharingCapability,                  Existing.LoopOverrideSharingCapability ),
            Existing.LoopSharingCapability                          = ISNULL( New.LoopSharingCapability,                          Existing.LoopSharingCapability ),
            Existing.MediaTranscription                             = ISNULL( New.MediaTranscription,                             Existing.MediaTranscription ),
            Existing.OverrideBlockUserInfoVisibility                = ISNULL( New.OverrideBlockUserInfoVisibility,                Existing.OverrideBlockUserInfoVisibility ),
            Existing.OverrideSharingCapability                      = ISNULL( New.OverrideSharingCapability,                      Existing.OverrideSharingCapability ),
            Existing.OverrideTenantAnonymousLinkExpirationPolicy    = ISNULL( New.OverrideTenantAnonymousLinkExpirationPolicy,    Existing.OverrideTenantAnonymousLinkExpirationPolicy ),
            Existing.OverrideTenantExternalUserExpirationPolicy     = ISNULL( New.OverrideTenantExternalUserExpirationPolicy,     Existing.OverrideTenantExternalUserExpirationPolicy ),
            Existing.Owner                                          = ISNULL( New.Owner,                                          Existing.Owner ),
            Existing.PWAEnabled                                     = ISNULL( New.PWAEnabled,                                     Existing.PWAEnabled ),
            Existing.ReadOnlyAccessPolicy                           = ISNULL( New.ReadOnlyAccessPolicy,                           Existing.ReadOnlyAccessPolicy ),
            Existing.ReadOnlyForBlockDownloadPolicy                 = ISNULL( New.ReadOnlyForBlockDownloadPolicy,                 Existing.ReadOnlyForBlockDownloadPolicy ),
            Existing.ReadOnlyForUnmanagedDevices                    = ISNULL( New.ReadOnlyForUnmanagedDevices,                    Existing.ReadOnlyForUnmanagedDevices ),
            Existing.RelatedGroupId                                 = ISNULL( New.RelatedGroupId,                                 Existing.RelatedGroupId ),
            Existing.RequestFilesLinkEnabled                        = ISNULL( New.RequestFilesLinkEnabled,                        Existing.RequestFilesLinkEnabled ),
            Existing.RequestFilesLinkExpirationInDays               = ISNULL( New.RequestFilesLinkExpirationInDays,               Existing.RequestFilesLinkExpirationInDays ),
            Existing.RestrictedAccessControl                        = ISNULL( New.RestrictedAccessControl,                        Existing.RestrictedAccessControl ),
            Existing.RestrictedToRegion                             = ISNULL( New.RestrictedToRegion,                             Existing.RestrictedToRegion ),
            Existing.SensitivityLabel                               = ISNULL( New.SensitivityLabel,                               Existing.SensitivityLabel ),
            Existing.SharingAllowedDomainList                       = ISNULL( New.SharingAllowedDomainList,                       Existing.SharingAllowedDomainList ),
            Existing.SharingBlockedDomainList                       = ISNULL( New.SharingBlockedDomainList,                       Existing.SharingBlockedDomainList ),
            Existing.SharingCapability                              = ISNULL( New.SharingCapability,                              Existing.SharingCapability ),
            Existing.SharingDomainRestrictionMode                   = ISNULL( New.SharingDomainRestrictionMode,                   Existing.SharingDomainRestrictionMode ),
            Existing.SharingLockDownCanBeCleared                    = ISNULL( New.SharingLockDownCanBeCleared,                    Existing.SharingLockDownCanBeCleared ),
            Existing.SharingLockDownEnabled                         = ISNULL( New.SharingLockDownEnabled,                         Existing.SharingLockDownEnabled ),
            Existing.ShowPeoplePickerSuggestionsForGuestUsers       = ISNULL( New.ShowPeoplePickerSuggestionsForGuestUsers,       Existing.ShowPeoplePickerSuggestionsForGuestUsers ),
            Existing.SiteCreationSource                             = ISNULL( New.SiteCreationSource,                             Existing.SiteCreationSource ),
            Existing.SiteDefinedSharingCapability                   = ISNULL( New.SiteDefinedSharingCapability,                   Existing.SiteDefinedSharingCapability ),
            Existing.SiteId                                         = ISNULL( New.SiteId,                                         Existing.SiteId ),
            Existing.SiteUrl                                        = ISNULL( New.SiteUrl,                                        Existing.SiteUrl ),
            Existing.SocialBarOnSitePagesDisabled                   = ISNULL( New.SocialBarOnSitePagesDisabled,                   Existing.SocialBarOnSitePagesDisabled ),
            Existing.StorageMaximumLevel                            = ISNULL( New.StorageMaximumLevel,                            Existing.StorageMaximumLevel ),
            Existing.StorageQuotaType                               = ISNULL( New.StorageQuotaType,                               Existing.StorageQuotaType ),
            Existing.StorageUsage                                   = ISNULL( New.StorageUsage,                                   Existing.StorageUsage ),
            Existing.StorageWarningLevel                            = ISNULL( New.StorageWarningLevel,                            Existing.StorageWarningLevel ),
            Existing.TeamsChannelType                               = ISNULL( New.TeamsChannelType,                               Existing.TeamsChannelType ),
            Existing.Template                                       = ISNULL( New.Template,                                       Existing.Template ),
            Existing.TimeZoneId                                     = ISNULL( New.TimeZoneId,                                     Existing.TimeZoneId ),
            Existing.Title                                          = ISNULL( New.Title,                                          Existing.Title ),
            Existing.TotalFileCount                                 = ISNULL( New.TotalFileCount,                                 Existing.TotalFileCount ),
            Existing.WebsCount                                      = ISNULL( New.WebsCount,                                      Existing.WebsCount ),
            Existing.RowUpdated                                     = New.RowUpdated
    WHEN NOT MATCHED THEN 
        INSERT
        (
            AllowDownloadingNonWebViewableFiles,
            AllowEditing,
            AnonymousLinkExpirationInDays,
            AuthenticationContextLimitedAccess,
            AuthenticationContextName,
            BlockDownloadLinksFileType,
            BlockDownloadPolicy,
            BlockGuestsAsSiteAdmin,
            CommentsOnSitePagesDisabled,
            CompatibilityLevel,
            ConditionalAccessPolicy,
            CreatedDate,
            DefaultLinkPermission,
            DefaultLinkToExistingAccess,
            DefaultLinkToExistingAccessReset,
            DefaultShareLinkRole,
            DefaultShareLinkScope,
            DefaultSharingLinkType,
            DeletedDate,
            DenyAddAndCustomizePages,
            [Description],
            DisableAppViews,
            DisableCompanyWideSharingLinks,
            DisableFlows,
            ExcludeBlockDownloadPolicySiteOwners,
            ExternalUserExpirationInDays,
            Geolocation,
            GroupId,
            HasHolds,
            HubSiteId,
            IBMode,
            IsHubSite,
            IsTeamsChannelConnected,
            IsTeamsConnected,
            LastContentModifiedDate,
            Lcid,
            LimitedAccessFileType,
            ListsShowHeaderAndNavigation,
            LockIssue,
            LockState,
            LoopDefaultSharingLinkRole,
            LoopDefaultSharingLinkScope,
            LoopOverrideSharingCapability,
            LoopSharingCapability,
            MediaTranscription,
            OverrideBlockUserInfoVisibility,
            OverrideSharingCapability,
            OverrideTenantAnonymousLinkExpirationPolicy,
            OverrideTenantExternalUserExpirationPolicy,
            [Owner],
            PWAEnabled,
            ReadOnlyAccessPolicy,
            ReadOnlyForBlockDownloadPolicy,
            ReadOnlyForUnmanagedDevices,
            RelatedGroupId,
            RequestFilesLinkEnabled,
            RequestFilesLinkExpirationInDays,
            RestrictedAccessControl,
            RestrictedToRegion,
            SensitivityLabel,
            SharingAllowedDomainList,
            SharingBlockedDomainList,
            SharingCapability,
            SharingDomainRestrictionMode,
            SharingLockDownCanBeCleared,
            SharingLockDownEnabled,
            ShowPeoplePickerSuggestionsForGuestUsers,
            SiteCreationSource,
            SiteDefinedSharingCapability,
            SiteId,
            SiteUrl,
            SocialBarOnSitePagesDisabled,
            [Status],
            StorageMaximumLevel,
            StorageQuotaType,
            StorageUsage,
            StorageWarningLevel,
            TeamsChannelType,
            Template,
            TimeZoneId,
            Title,
            TotalFileCount,
            WebsCount,
            RowCreated,
            RowUpdated    
        )
        VALUES 
        (
            AllowDownloadingNonWebViewableFiles,
            AllowEditing,
            AnonymousLinkExpirationInDays,
            AuthenticationContextLimitedAccess,
            AuthenticationContextName,
            BlockDownloadLinksFileType,
            BlockDownloadPolicy,
            BlockGuestsAsSiteAdmin,
            CommentsOnSitePagesDisabled,
            CompatibilityLevel,
            ConditionalAccessPolicy,
            CreatedDate,
            DefaultLinkPermission,
            DefaultLinkToExistingAccess,
            DefaultLinkToExistingAccessReset,
            DefaultShareLinkRole,
            DefaultShareLinkScope,
            DefaultSharingLinkType,
            DeletedDate,
            DenyAddAndCustomizePages,
            [Description],
            DisableAppViews,
            DisableCompanyWideSharingLinks,
            DisableFlows,
            ExcludeBlockDownloadPolicySiteOwners,
            ExternalUserExpirationInDays,
            Geolocation,
            GroupId,
            HasHolds,
            HubSiteId,
            IBMode,
            IsHubSite,
            IsTeamsChannelConnected,
            IsTeamsConnected,
            LastContentModifiedDate,
            Lcid,
            LimitedAccessFileType,
            ListsShowHeaderAndNavigation,
            LockIssue,
            LockState,
            LoopDefaultSharingLinkRole,
            LoopDefaultSharingLinkScope,
            LoopOverrideSharingCapability,
            LoopSharingCapability,
            MediaTranscription,
            OverrideBlockUserInfoVisibility,
            OverrideSharingCapability,
            OverrideTenantAnonymousLinkExpirationPolicy,
            OverrideTenantExternalUserExpirationPolicy,
            [Owner],
            PWAEnabled,
            ReadOnlyAccessPolicy,
            ReadOnlyForBlockDownloadPolicy,
            ReadOnlyForUnmanagedDevices,
            RelatedGroupId,
            RequestFilesLinkEnabled,
            RequestFilesLinkExpirationInDays,
            RestrictedAccessControl,
            RestrictedToRegion,
            SensitivityLabel,
            SharingAllowedDomainList,
            SharingBlockedDomainList,
            SharingCapability,
            SharingDomainRestrictionMode,
            SharingLockDownCanBeCleared,
            SharingLockDownEnabled,
            ShowPeoplePickerSuggestionsForGuestUsers,
            SiteCreationSource,
            SiteDefinedSharingCapability,
            SiteId,
            SiteUrl,
            SocialBarOnSitePagesDisabled,
            [Status],
            StorageMaximumLevel,
            StorageQuotaType,
            StorageUsage,
            StorageWarningLevel,
            TeamsChannelType,
            Template,
            TimeZoneId,
            Title,
            TotalFileCount,
            WebsCount,
            RowCreated,
            RowUpdated
        );
END