CREATE OR ALTER PROCEDURE [site].[proc_AddOrUpdateActiveSite]
    @json nvarchar(max)
AS
BEGIN

    DECLARE @timestamp datetime2(7) = GETUTCDATE()

    ;WITH
        sites
        AS
        (
            SELECT
                AllowDownloadingNonWebViewableFiles,
                AllowEditing,
                AnonymousLinkExpirationInDays,
                AuthContextStrength,
                AuthenticationContextLimitedAccess,
                AuthenticationContextName,
                BlockDownloadLinksFileType,
                BlockDownloadPolicy,
                BlockGuestsAsSiteAdmin,
                CommentsOnSitePagesDisabled,
                CompatibilityLevel,
                ConditionalAccessPolicy,
                CreatedDate,
                DefaultLinkPermission,
                DefaultLinkToExistingAccess,
                DefaultLinkToExistingAccessReset,
                DefaultShareLinkRole,
                DefaultShareLinkScope,
                DefaultSharingLinkType,
                DeletedDate,
                DenyAddAndCustomizePages,
                [Description],
                DisableCompanyWideSharingLinks,
                ExcludeBlockDownloadPolicySiteOwners,
                ExcludedBlockDownloadGroupIds,
                ExternalUserExpirationInDays,
                GeoLocation,
                GroupId = ISNULL(GroupId, '00000000-0000-0000-0000-000000000000'),
                HasHolds,
                HubSiteId = ISNULL(HubSiteId, '00000000-0000-0000-0000-000000000000'),
                IBMode = site.InformationBarrierMode.Id,
                IsHubSite,
                IsInRecycleBin,
                IsTeamsChannelConnected,
                IsTeamsConnected,
                LastContentModifiedDate,
                LastSecurityModifiedDate,
                Lcid,
                LimitedAccessFileType,
                LockIssue,
                LockState = site.LockState.Id,
                LoopDefaultSharingLinkRole,
                LoopDefaultSharingLinkScope,
                LoopOverrideSharingCapability,
                LoopSharingCapability,
                MediaTranscription,
                OverrideBlockUserInfoVisibility,
                OverrideSharingCapability,
                OverrideTenantAnonymousLinkExpirationPolicy,
                OverrideTenantExternalUserExpirationPolicy,
                [Owner] = ISNULL([Owner], '00000000-0000-0000-0000-000000000000'),
                PWAEnabled,
                ReadOnlyAccessPolicy,
                ReadOnlyForUnmanagedDevices,
                RelatedGroupId = ISNULL(RelatedGroupId, '00000000-0000-0000-0000-000000000000'),
                RequestFilesLinkEnabled,
                RequestFilesLinkExpirationInDays,
                RestrictedAccessControl,
                RestrictedAccessControlGroups,
                RestrictedToRegion,
                SensitivityLabel = ISNULL(SensitivityLabel, '00000000-0000-0000-0000-000000000000'),
                ShareByEmailEnabled,
                ShareByLinkEnabled,
                SharingAllowedDomainList,
                SharingBlockedDomainList,
                SharingCapability,
                SharingDomainRestrictionMode,
                SharingLockDownCanBeCleared,
                SharingLockDownEnabled,
                ShowPeoplePickerSuggestionsForGuestUsers,
                SiteCreationSource = ISNULL(SiteCreationSource, '00000000-0000-0000-0000-000000000000'),
                SiteDefinedSharingCapability,
                SiteId,
                SiteUrl,
                SocialBarOnSitePagesDisabled,
                [Status],
                StorageMaximumLevel,
                StorageQuotaType,
                StorageUsage,
                StorageWarningLevel,
                TeamsChannelType = TeamsChannelType,
                Template,
                TimeZoneId,
                Title,
                TotalFileCount,
                WebsCount,
                RowCreated = @timestamp,
                RowUpdated = @timestamp
            FROM
                OPENJSON (@json, N'lax $') WITH 
                (
                    AllowDownloadingNonWebViewableFiles            bit              N'$.AllowDownloadingNonWebViewableFiles',
                    AllowEditing                                   bit              N'$.AllowEditing',
                    AnonymousLinkExpirationInDays                  int              N'$.AnonymousLinkExpirationInDays',
                    AuthContextStrength                            nvarchar(500)    N'$.AuthContextStrength',
                    AuthenticationContextLimitedAccess             bit              N'$.AuthenticationContextLimitedAccess',
                    AuthenticationContextName                      nvarchar(255)    N'$.AuthenticationContextName',
                    BlockDownloadLinksFileType                     int              N'$.BlockDownloadLinksFileType',
                    BlockDownloadPolicy                            bit              N'$.BlockDownloadPolicy',
                    BlockGuestsAsSiteAdmin                         int              N'$.BlockGuestsAsSiteAdmin',
                    CommentsOnSitePagesDisabled                    bit              N'$.CommentsOnSitePagesDisabled',
                    CompatibilityLevel                             int              N'$.CompatibilityLevel',
                    ConditionalAccessPolicy                        int              N'$.ConditionalAccessPolicy',
                    CreatedDate                                    datetime2(7)     N'$.CreatedDate',
                    DefaultLinkPermission                          int              N'$.DefaultLinkPermission',
                    DefaultLinkToExistingAccess                    bit              N'$.DefaultLinkToExistingAccess',
                    DefaultLinkToExistingAccessReset               bit              N'$.DefaultLinkToExistingAccessReset',
                    DefaultShareLinkRole                           int              N'$.DefaultShareLinkRole',
                    DefaultShareLinkScope                          int              N'$.DefaultShareLinkScope',
                    DefaultSharingLinkType                         int              N'$.DefaultSharingLinkType',
                    DeletedDate                                    datetime2(7)     N'$.DeletedDate',
                    DenyAddAndCustomizePages                       bit              N'$.DenyAddAndCustomizePages',
                    [Description]                                  nvarchar(500)    N'$.Description',
                    DisableCompanyWideSharingLinks                 bit              N'$.DisableCompanyWideSharingLinks',
                    ExcludeBlockDownloadPolicySiteOwners           bit              N'$.ExcludeBlockDownloadPolicySiteOwners',
                    ExcludedBlockDownloadGroupIds                  nvarchar(4000)   N'$.ExcludedBlockDownloadGroupIds',
                    ExternalUserExpirationInDays                   int              N'$.ExternalUserExpirationInDays',
                    GeoLocation                                    nvarchar(10)     N'$.GeoLocation',
                    GroupId                                        uniqueidentifier N'$.GroupId',
                    HasHolds                                       bit              N'$.HasHolds',
                    HubSiteId                                      uniqueidentifier N'$.HubSiteId',
                    IBMode                                         nvarchar(100)    N'$.IBMode',
                    IsHubSite                                      bit              N'$.IsHubSite',
                    IsInRecycleBin                                 bit              N'$.IsInRecycleBin',
                    IsTeamsChannelConnected                        bit              N'$.IsTeamsChannelConnected',
                    IsTeamsConnected                               bit              N'$.IsTeamsConnected',
                    LastContentModifiedDate                        datetime2(7)     N'$.LastContentModifiedDate',
                    LastSecurityModifiedDate                       datetime2(7)     N'$.LastSecurityModifiedDate',
                    Lcid                                           int              N'$.Lcid',
                    LimitedAccessFileType                          int              N'$.LimitedAccessFileType',
                    LockIssue                                      nvarchar(450)    N'$.LockIssue',
                    LockState                                      nvarchar(100)    N'$.LockState',
                    LoopDefaultSharingLinkRole                     int              N'$.LoopDefaultSharingLinkRole',
                    LoopDefaultSharingLinkScope                    int              N'$.LoopDefaultSharingLinkScope',
                    LoopOverrideSharingCapability                  bit              N'$.LoopOverrideSharingCapability',
                    LoopSharingCapability                          int              N'$.LoopSharingCapability',
                    MediaTranscription                             int              N'$.MediaTranscription',
                    OverrideBlockUserInfoVisibility                int              N'$.OverrideBlockUserInfoVisibility',
                    OverrideSharingCapability                      bit              N'$.OverrideSharingCapability',
                    OverrideTenantAnonymousLinkExpirationPolicy    bit              N'$.OverrideTenantAnonymousLinkExpirationPolicy',
                    OverrideTenantExternalUserExpirationPolicy     bit              N'$.OverrideTenantExternalUserExpirationPolicy',
                    [Owner]                                        uniqueidentifier N'$.Owner',
                    PWAEnabled                                     int              N'$.PWAEnabled',
                    ReadOnlyAccessPolicy                           bit              N'$.ReadOnlyAccessPolicy',
                    ReadOnlyForUnmanagedDevices                    bit              N'$.ReadOnlyForUnmanagedDevices',
                    RelatedGroupId                                 uniqueidentifier N'$.RelatedGroupId',
                    RequestFilesLinkEnabled                        bit              N'$.RequestFilesLinkEnabled',
                    RequestFilesLinkExpirationInDays               int              N'$.RequestFilesLinkExpirationInDays',
                    RestrictedAccessControl                        bit              N'$.RestrictedAccessControl',
                    RestrictedAccessControlGroups                  nvarchar(4000)   N'$.RestrictedAccessControlGroups',
                    RestrictedToRegion                             int              N'$.RestrictedToRegion',
                    SensitivityLabel                               uniqueidentifier N'$.SensitivityLabel',
                    ShareByEmailEnabled                            bit              N'$.ShareByEmailEnabled',
                    ShareByLinkEnabled                             bit              N'$.ShareByLinkEnabled',
                    SharingAllowedDomainList                       nvarchar(max)    N'$.SharingAllowedDomainList',
                    SharingBlockedDomainList                       nvarchar(max)    N'$.SharingAllowedDomainList',
                    SharingCapability                              int              N'$.SharingCapability',
                    SharingDomainRestrictionMode                   int              N'$.SharingDomainRestrictionMode',
                    SharingLockDownCanBeCleared                    bit              N'$.SharingLockDownCanBeCleared',
                    SharingLockDownEnabled                         bit              N'$.SharingLockDownEnabled',
                    ShowPeoplePickerSuggestionsForGuestUsers       bit              N'$.ShowPeoplePickerSuggestionsForGuestUsers',
                    SiteCreationSource                             uniqueidentifier N'$.SiteCreationSource',
                    SiteDefinedSharingCapability                   int              N'$.SiteDefinedSharingCapability',
                    SiteId                                         uniqueidentifier N'$.SiteId',
                    SiteUrl                                        nvarchar(450)    N'$.SiteUrl',
                    SocialBarOnSitePagesDisabled                   bit              N'$.SocialBarOnSitePagesDisabled',
                    [Status]                                       nvarchar(255)    N'$.Status',
                    StorageMaximumLevel                            bigint           N'$.StorageMaximumLevel',
                    StorageQuotaType                               nvarchar(255)    N'$.StorageQuotaType',
                    StorageUsage                                   bigint           N'$.StorageUsage',
                    StorageWarningLevel                            bigint           N'$.StorageWarningLevel',
                    TeamsChannelType                               int              N'$.TeamsChannelType',
                    Template                                       nvarchar(255)    N'$.Template',
                    TimeZoneId                                     int              N'$.TimeZoneId',
                    Title                                          nvarchar(255)    N'$.Title',
                    TotalFileCount                                 int              N'$.TotalFileCount',
                    WebsCount                                      int              N'$.WebsCount'
                ) js
                LEFT JOIN
                site.InformationBarrierMode ON js.IBMode = site.InformationBarrierMode.InformationBarrierMode
                LEFT JOIN
                site.LockState ON js.LockState = site.LockState.LockState
        )
   
   
    MERGE INTO site.SiteCollection AS Existing
    USING sites AS New
    ON New.SiteId = Existing.SiteId
    WHEN MATCHED THEN
        UPDATE SET
            Existing.[Description]                                  = ISNULL( New.[Description],                                  Existing.[Description] ),
            Existing.[Status]                                       = ISNULL( New.[Status],                                       Existing.[Status] ),
            Existing.AllowDownloadingNonWebViewableFiles            = ISNULL( New.AllowDownloadingNonWebViewableFiles,            Existing.AllowDownloadingNonWebViewableFiles ),
            Existing.AllowEditing                                   = ISNULL( New.AllowEditing,                                   Existing.AllowEditing ),
            Existing.AnonymousLinkExpirationInDays                  = ISNULL( New.AnonymousLinkExpirationInDays,                  Existing.AnonymousLinkExpirationInDays ),
            Existing.AuthContextStrength                            = ISNULL( New.AuthContextStrength,                            Existing.AuthContextStrength ),
            Existing.AuthenticationContextLimitedAccess             = ISNULL( New.AuthenticationContextLimitedAccess,             Existing.AuthenticationContextLimitedAccess ),
            Existing.AuthenticationContextName                      = ISNULL( New.AuthenticationContextName,                      Existing.AuthenticationContextName ),
            Existing.BlockDownloadLinksFileType                     = ISNULL( New.BlockDownloadLinksFileType,                     Existing.BlockDownloadLinksFileType ),
            Existing.BlockDownloadPolicy                            = ISNULL( New.BlockDownloadPolicy,                            Existing.BlockDownloadPolicy ),
            Existing.BlockGuestsAsSiteAdmin                         = ISNULL( New.BlockGuestsAsSiteAdmin,                         Existing.BlockGuestsAsSiteAdmin ),
            Existing.CommentsOnSitePagesDisabled                    = ISNULL( New.CommentsOnSitePagesDisabled,                    Existing.CommentsOnSitePagesDisabled ),
            Existing.CompatibilityLevel                             = ISNULL( New.CompatibilityLevel,                             Existing.CompatibilityLevel ),
            Existing.ConditionalAccessPolicy                        = ISNULL( New.ConditionalAccessPolicy,                        Existing.ConditionalAccessPolicy ),
            Existing.CreatedDate                                    = ISNULL( New.CreatedDate,                                    Existing.CreatedDate ),
            Existing.DefaultLinkPermission                          = ISNULL( New.DefaultLinkPermission,                          Existing.DefaultLinkPermission ),
            Existing.DefaultLinkToExistingAccess                    = ISNULL( New.DefaultLinkToExistingAccess,                    Existing.DefaultLinkToExistingAccess ),
            Existing.DefaultLinkToExistingAccessReset               = ISNULL( New.DefaultLinkToExistingAccessReset,               Existing.DefaultLinkToExistingAccessReset ),
            Existing.DefaultShareLinkRole                           = ISNULL( New.DefaultShareLinkRole,                           Existing.DefaultShareLinkRole ),
            Existing.DefaultShareLinkScope                          = ISNULL( New.DefaultShareLinkScope,                          Existing.DefaultShareLinkScope ),
            Existing.DefaultSharingLinkType                         = ISNULL( New.DefaultSharingLinkType,                         Existing.DefaultSharingLinkType ),
            Existing.DeletedDate                                    = New.DeletedDate,
            Existing.DenyAddAndCustomizePages                       = ISNULL( New.DenyAddAndCustomizePages,                       Existing.DenyAddAndCustomizePages ),
            Existing.DisableCompanyWideSharingLinks                 = ISNULL( New.DisableCompanyWideSharingLinks,                 Existing.DisableCompanyWideSharingLinks ),
            Existing.ExcludeBlockDownloadPolicySiteOwners           = ISNULL( New.ExcludeBlockDownloadPolicySiteOwners,           Existing.ExcludeBlockDownloadPolicySiteOwners ),
            Existing.ExcludedBlockDownloadGroupIds                  = ISNULL( New.ExcludedBlockDownloadGroupIds,                  Existing.ExcludedBlockDownloadGroupIds ),
            Existing.ExternalUserExpirationInDays                   = ISNULL( New.ExternalUserExpirationInDays,                   Existing.ExternalUserExpirationInDays ),
            Existing.GeoLocation                                    = ISNULL( New.GeoLocation,                                    Existing.GeoLocation ),
            Existing.GroupId                                        = ISNULL( New.GroupId,                                        Existing.GroupId ),
            Existing.HasHolds                                       = ISNULL( New.HasHolds,                                       Existing.HasHolds ),
            Existing.HubSiteId                                      = ISNULL( New.HubSiteId,                                      Existing.HubSiteId ),
            Existing.IBMode                                         = ISNULL( New.IBMode,                                         Existing.IBMode ),
            Existing.IsHubSite                                      = ISNULL( New.IsHubSite,                                      Existing.IsHubSite ),
            Existing.IsInRecycleBin                                 = ISNULL( New.IsInRecycleBin,                                 Existing.IsInRecycleBin ),
            Existing.IsTeamsChannelConnected                        = ISNULL( New.IsTeamsChannelConnected,                        Existing.IsTeamsChannelConnected ),
            Existing.IsTeamsConnected                               = ISNULL( New.IsTeamsConnected,                               Existing.IsTeamsConnected ),
            Existing.LastContentModifiedDate                        = ISNULL( New.LastContentModifiedDate,                        Existing.LastContentModifiedDate ),
            Existing.LastSecurityModifiedDate                       = ISNULL( New.LastSecurityModifiedDate,                       Existing.LastSecurityModifiedDate ),
            Existing.Lcid                                           = ISNULL( New.Lcid,                                           Existing.Lcid ),
            Existing.LimitedAccessFileType                          = ISNULL( New.LimitedAccessFileType,                          Existing.LimitedAccessFileType ),
            Existing.LockIssue                                      = ISNULL( New.LockIssue,                                      Existing.LockIssue ),
            Existing.LockState                                      = ISNULL( New.LockState,                                      Existing.LockState ),
            Existing.LoopDefaultSharingLinkRole                     = ISNULL( New.LoopDefaultSharingLinkRole,                     Existing.LoopDefaultSharingLinkRole ),
            Existing.LoopDefaultSharingLinkScope                    = ISNULL( New.LoopDefaultSharingLinkScope,                    Existing.LoopDefaultSharingLinkScope ),
            Existing.LoopOverrideSharingCapability                  = ISNULL( New.LoopOverrideSharingCapability,                  Existing.LoopOverrideSharingCapability ),
            Existing.LoopSharingCapability                          = ISNULL( New.LoopSharingCapability,                          Existing.LoopSharingCapability ),
            Existing.MediaTranscription                             = ISNULL( New.MediaTranscription,                             Existing.MediaTranscription ),
            Existing.OverrideBlockUserInfoVisibility                = ISNULL( New.OverrideBlockUserInfoVisibility,                Existing.OverrideBlockUserInfoVisibility ),
            Existing.OverrideSharingCapability                      = ISNULL( New.OverrideSharingCapability,                      Existing.OverrideSharingCapability ),
            Existing.OverrideTenantAnonymousLinkExpirationPolicy    = ISNULL( New.OverrideTenantAnonymousLinkExpirationPolicy,    Existing.OverrideTenantAnonymousLinkExpirationPolicy ),
            Existing.OverrideTenantExternalUserExpirationPolicy     = ISNULL( New.OverrideTenantExternalUserExpirationPolicy,     Existing.OverrideTenantExternalUserExpirationPolicy ),
            Existing.Owner                                          = ISNULL( New.Owner,                                          Existing.Owner ),
            Existing.PWAEnabled                                     = ISNULL( New.PWAEnabled,                                     Existing.PWAEnabled ),
            Existing.ReadOnlyAccessPolicy                           = ISNULL( New.ReadOnlyAccessPolicy,                           Existing.ReadOnlyAccessPolicy ),
            Existing.ReadOnlyForUnmanagedDevices                    = ISNULL( New.ReadOnlyForUnmanagedDevices,                    Existing.ReadOnlyForUnmanagedDevices ),
            Existing.RelatedGroupId                                 = ISNULL( New.RelatedGroupId,                                 Existing.RelatedGroupId ),
            Existing.RequestFilesLinkEnabled                        = ISNULL( New.RequestFilesLinkEnabled,                        Existing.RequestFilesLinkEnabled ),
            Existing.RequestFilesLinkExpirationInDays               = ISNULL( New.RequestFilesLinkExpirationInDays,               Existing.RequestFilesLinkExpirationInDays ),
            Existing.RestrictedAccessControl                        = ISNULL( New.RestrictedAccessControl,                        Existing.RestrictedAccessControl ),
            Existing.RestrictedAccessControlGroups                  = ISNULL( New.RestrictedAccessControlGroups,                  Existing.RestrictedAccessControlGroups ),
            Existing.RestrictedToRegion                             = ISNULL( New.RestrictedToRegion,                             Existing.RestrictedToRegion ),
            Existing.SensitivityLabel                               = ISNULL( New.SensitivityLabel,                               Existing.SensitivityLabel ),
            Existing.ShareByEmailEnabled                            = ISNULL( New.ShareByEmailEnabled,                            Existing.ShareByEmailEnabled ),
            Existing.ShareByLinkEnabled                             = ISNULL( New.ShareByLinkEnabled,                             Existing.ShareByLinkEnabled ),
            Existing.SharingAllowedDomainList                       = ISNULL( New.SharingAllowedDomainList,                       Existing.SharingAllowedDomainList ),
            Existing.SharingBlockedDomainList                       = ISNULL( New.SharingBlockedDomainList,                       Existing.SharingBlockedDomainList ),
            Existing.SharingCapability                              = ISNULL( New.SharingCapability,                              Existing.SharingCapability ),
            Existing.SharingDomainRestrictionMode                   = ISNULL( New.SharingDomainRestrictionMode,                   Existing.SharingDomainRestrictionMode ),
            Existing.SharingLockDownCanBeCleared                    = ISNULL( New.SharingLockDownCanBeCleared,                    Existing.SharingLockDownCanBeCleared ),
            Existing.SharingLockDownEnabled                         = ISNULL( New.SharingLockDownEnabled,                         Existing.SharingLockDownEnabled ),
            Existing.ShowPeoplePickerSuggestionsForGuestUsers       = ISNULL( New.ShowPeoplePickerSuggestionsForGuestUsers,       Existing.ShowPeoplePickerSuggestionsForGuestUsers ),
            Existing.SiteCreationSource                             = ISNULL( New.SiteCreationSource,                             Existing.SiteCreationSource ),
            Existing.SiteDefinedSharingCapability                   = ISNULL( New.SiteDefinedSharingCapability,                   Existing.SiteDefinedSharingCapability ),
            Existing.SiteId                                         = ISNULL( New.SiteId,                                         Existing.SiteId ),
            Existing.SiteUrl                                        = ISNULL( New.SiteUrl,                                        Existing.SiteUrl ),
            Existing.SocialBarOnSitePagesDisabled                   = ISNULL( New.SocialBarOnSitePagesDisabled,                   Existing.SocialBarOnSitePagesDisabled ),
            Existing.StorageMaximumLevel                            = ISNULL( New.StorageMaximumLevel,                            Existing.StorageMaximumLevel ),
            Existing.StorageQuotaType                               = ISNULL( New.StorageQuotaType,                               Existing.StorageQuotaType ),
            Existing.StorageUsage                                   = ISNULL( New.StorageUsage,                                   Existing.StorageUsage ),
            Existing.StorageWarningLevel                            = ISNULL( New.StorageWarningLevel,                            Existing.StorageWarningLevel ),
            Existing.TeamsChannelType                               = ISNULL( New.TeamsChannelType,                               Existing.TeamsChannelType ),
            Existing.Template                                       = ISNULL( New.Template,                                       Existing.Template ),
            Existing.TimeZoneId                                     = ISNULL( New.TimeZoneId,                                     Existing.TimeZoneId ),
            Existing.Title                                          = ISNULL( New.Title,                                          Existing.Title ),
            Existing.TotalFileCount                                 = ISNULL( New.TotalFileCount,                                 Existing.TotalFileCount ),
            Existing.WebsCount                                      = ISNULL( New.WebsCount,                                      Existing.WebsCount ),
            Existing.RowUpdated                                     = New.RowUpdated
    WHEN NOT MATCHED THEN 
        INSERT
        (
            AllowDownloadingNonWebViewableFiles,
            AllowEditing,
            AnonymousLinkExpirationInDays,
            AuthContextStrength,
            AuthenticationContextLimitedAccess,
            AuthenticationContextName,
            BlockDownloadLinksFileType,
            BlockDownloadPolicy,
            BlockGuestsAsSiteAdmin,
            CommentsOnSitePagesDisabled,
            CompatibilityLevel,
            ConditionalAccessPolicy,
            CreatedDate,
            DefaultLinkPermission,
            DefaultLinkToExistingAccess,
            DefaultLinkToExistingAccessReset,
            DefaultShareLinkRole,
            DefaultShareLinkScope,
            DefaultSharingLinkType,
            DeletedDate,
            DenyAddAndCustomizePages,
            [Description],
            DisableCompanyWideSharingLinks,
            ExcludeBlockDownloadPolicySiteOwners,
            ExcludedBlockDownloadGroupIds,
            ExternalUserExpirationInDays,
            GeoLocation,
            GroupId,
            HasHolds,
            HubSiteId,
            IBMode,
            IsHubSite,
            IsInRecycleBin,
            IsTeamsChannelConnected,
            IsTeamsConnected,
            LastContentModifiedDate,
            LastSecurityModifiedDate,
            Lcid,
            LimitedAccessFileType,
            LockIssue,
            LockState,
            LoopDefaultSharingLinkRole,
            LoopDefaultSharingLinkScope,
            LoopOverrideSharingCapability,
            LoopSharingCapability,
            MediaTranscription,
            OverrideBlockUserInfoVisibility,
            OverrideSharingCapability,
            OverrideTenantAnonymousLinkExpirationPolicy,
            OverrideTenantExternalUserExpirationPolicy,
            [Owner],
            PWAEnabled,
            ReadOnlyAccessPolicy,
            ReadOnlyForUnmanagedDevices,
            RelatedGroupId,
            RequestFilesLinkEnabled,
            RequestFilesLinkExpirationInDays,
            RestrictedAccessControl,
            RestrictedAccessControlGroups,
            RestrictedToRegion,
            SensitivityLabel,
            ShareByEmailEnabled,
            ShareByLinkEnabled,
            SharingAllowedDomainList,
            SharingBlockedDomainList,
            SharingCapability,
            SharingDomainRestrictionMode,
            SharingLockDownCanBeCleared,
            SharingLockDownEnabled,
            ShowPeoplePickerSuggestionsForGuestUsers,
            SiteCreationSource,
            SiteDefinedSharingCapability,
            SiteId,
            SiteUrl,
            SocialBarOnSitePagesDisabled,
            [Status],
            StorageMaximumLevel,
            StorageQuotaType,
            StorageUsage,
            StorageWarningLevel,
            TeamsChannelType,
            Template,
            TimeZoneId,
            Title,
            TotalFileCount,
            WebsCount,
            RowCreated,
            RowUpdated    
        )
        VALUES 
        (
            AllowDownloadingNonWebViewableFiles,
            AllowEditing,
            AnonymousLinkExpirationInDays,
            AuthContextStrength,
            AuthenticationContextLimitedAccess,
            AuthenticationContextName,
            BlockDownloadLinksFileType,
            BlockDownloadPolicy,
            BlockGuestsAsSiteAdmin,
            CommentsOnSitePagesDisabled,
            CompatibilityLevel,
            ConditionalAccessPolicy,
            CreatedDate,
            DefaultLinkPermission,
            DefaultLinkToExistingAccess,
            DefaultLinkToExistingAccessReset,
            DefaultShareLinkRole,
            DefaultShareLinkScope,
            DefaultSharingLinkType,
            DeletedDate,
            DenyAddAndCustomizePages,
            [Description],
            DisableCompanyWideSharingLinks,
            ExcludeBlockDownloadPolicySiteOwners,
            ExcludedBlockDownloadGroupIds,
            ExternalUserExpirationInDays,
            GeoLocation,
            GroupId,
            HasHolds,
            HubSiteId,
            IBMode,
            IsHubSite,
            IsInRecycleBin,
            IsTeamsChannelConnected,
            IsTeamsConnected,
            LastContentModifiedDate,
            LastSecurityModifiedDate,
            Lcid,
            LimitedAccessFileType,
            LockIssue,
            LockState,
            LoopDefaultSharingLinkRole,
            LoopDefaultSharingLinkScope,
            LoopOverrideSharingCapability,
            LoopSharingCapability,
            MediaTranscription,
            OverrideBlockUserInfoVisibility,
            OverrideSharingCapability,
            OverrideTenantAnonymousLinkExpirationPolicy,
            OverrideTenantExternalUserExpirationPolicy,
            [Owner],
            PWAEnabled,
            ReadOnlyAccessPolicy,
            ReadOnlyForUnmanagedDevices,
            RelatedGroupId,
            RequestFilesLinkEnabled,
            RequestFilesLinkExpirationInDays,
            RestrictedAccessControl,
            RestrictedAccessControlGroups,
            RestrictedToRegion,
            SensitivityLabel,
            ShareByEmailEnabled,
            ShareByLinkEnabled,
            SharingAllowedDomainList,
            SharingBlockedDomainList,
            SharingCapability,
            SharingDomainRestrictionMode,
            SharingLockDownCanBeCleared,
            SharingLockDownEnabled,
            ShowPeoplePickerSuggestionsForGuestUsers,
            SiteCreationSource,
            SiteDefinedSharingCapability,
            SiteId,
            SiteUrl,
            SocialBarOnSitePagesDisabled,
            [Status],
            StorageMaximumLevel,
            StorageQuotaType,
            StorageUsage,
            StorageWarningLevel,
            TeamsChannelType,
            Template,
            TimeZoneId,
            Title,
            TotalFileCount,
            WebsCount,
            RowCreated,
            RowUpdated
        );
END