IF OBJECT_ID('site.SiteCollection', 'U') IS NULL
BEGIN
   CREATE TABLE site.SiteCollection
   (
      SiteId                                         uniqueidentifier NOT NULL,
      SiteUrl                                        nvarchar(450)    NULL,
      GroupId                                        uniqueidentifier NULL,
      AllowDownloadingNonWebViewableFiles            bit              NULL,
      AllowEditing                                   bit              NULL,
      AnonymousLinkExpirationInDays                  int              NULL,
      AuthenticationContextLimitedAccess             bit              NULL,
      AuthenticationContextName                      nvarchar(255)    NULL,
      BlockDownloadLinksFileType                     int              NULL,
      BlockDownloadPolicy                            bit              NULL,
      BlockGuestsAsSiteAdmin                         int              NULL,
      CommentsOnSitePagesDisabled                    bit              NULL,
      CompatibilityLevel                             int              NULL,
      ConditionalAccessPolicy                        int              NULL,
      CreatedDate                                    datetime2(7)     NULL,
      DefaultLinkPermission                          int              NULL,
      DefaultLinkToExistingAccess                    bit              NULL,
      DefaultLinkToExistingAccessReset               bit              NULL,
      DefaultShareLinkRole                           int              NULL,
      DefaultShareLinkScope                          int              NULL,
      DefaultSharingLinkType                         int              NULL,
      DeletedDate                                    datetime2(7)     NULL,
      DenyAddAndCustomizePages                       bit              NULL,
      [Description]                                  nvarchar(500)    NULL,
      DisableAppViews                                int              NULL,
      DisableCompanyWideSharingLinks                 bit              NULL,
      DisableFlows                                   int              NULL,
      ExcludeBlockDownloadPolicySiteOwners           bit              NULL,
      ExternalUserExpirationInDays                   int              NULL,
      Geolocation                                    nvarchar(10)     NULL,
      HasHolds                                       bit              NULL,
      HubSiteId                                      uniqueidentifier NULL,
      IBMode                                         int              NULL,
      IsHubSite                                      bit              NULL,
      IsTeamsChannelConnected                        bit              NULL,
      IsTeamsConnected                               bit              NULL,
      LastContentModifiedDate                        datetime2(7)     NULL,
      Lcid                                           int              NULL,
      LimitedAccessFileType                          int              NULL,
      ListsShowHeaderAndNavigation                   bit              NULL,
      LockIssue                                      nvarchar(450)    NULL,
      LockState                                      int              NULL,
      LoopDefaultSharingLinkRole                     int              NULL,
      LoopDefaultSharingLinkScope                    int              NULL,
      LoopOverrideSharingCapability                  bit              NULL,
      LoopSharingCapability                          int              NULL,
      MediaTranscription                             int              NULL,
      OverrideBlockUserInfoVisibility                int              NULL,
      OverrideSharingCapability                      bit              NULL,
      OverrideTenantAnonymousLinkExpirationPolicy    bit              NULL,
      OverrideTenantExternalUserExpirationPolicy     bit              NULL,
      [Owner]                                        uniqueidentifier NULL,
      PWAEnabled                                     int              NULL,
      ReadOnlyAccessPolicy                           bit              NULL,
      ReadOnlyForBlockDownloadPolicy                 bit              NULL,
      ReadOnlyForUnmanagedDevices                    bit              NULL,
      RelatedGroupId                                 uniqueidentifier NULL,
      RequestFilesLinkEnabled                        bit              NULL,
      RequestFilesLinkExpirationInDays               int              NULL,
      RestrictedAccessControl                        bit              NULL,
      RestrictedToRegion                             int              NULL,
      SensitivityLabel                               uniqueidentifier NULL,
      SharingAllowedDomainList                       nvarchar(max)    NULL,
      SharingBlockedDomainList                       nvarchar(max)    NULL,
      SharingCapability                              int              NULL,
      SharingDomainRestrictionMode                   int              NULL,
      SharingLockDownCanBeCleared                    bit              NULL,
      SharingLockDownEnabled                         bit              NULL,
      ShowPeoplePickerSuggestionsForGuestUsers       bit              NULL,
      SiteCreationSource                             uniqueidentifier NULL,
      SiteDefinedSharingCapability                   int              NULL,
      SocialBarOnSitePagesDisabled                   bit              NULL,
      [Status]                                       nvarchar(100)    NULL,
      StorageMaximumLevel                            bigint           NULL,
      StorageQuotaType                               nvarchar(255)    NULL,
      StorageUsage                                   bigint           NULL,
      StorageWarningLevel                            bigint           NULL,
      TeamsChannelType                               int              NULL,
      Template                                       nvarchar(255)    NULL,
      TimeZoneId                                     int              NULL,
      Title                                          nvarchar(255)    NULL,
      TotalFileCount                                 int              NULL,
      WebsCount                                      int              NULL,
      RowCreated                                     datetime2(7)     NOT NULL,
      RowUpdated                                     datetime2(7)     NOT NULL,
      CONSTRAINT PK_Entity_SiteId PRIMARY KEY CLUSTERED (SiteId ASC)
   )

   CREATE NONCLUSTERED INDEX IX_SiteCollection_GroupId     ON site.SiteCollection (GroupId     ASC)
   CREATE NONCLUSTERED INDEX IX_SiteCollection_SiteUrl     ON site.SiteCollection (SiteUrl     ASC)
   CREATE NONCLUSTERED INDEX IX_SiteCollection_Template    ON site.SiteCollection (Template    ASC)
   CREATE NONCLUSTERED INDEX IX_SiteCollection_DeletedDate ON site.SiteCollection (DeletedDate ASC)
   CREATE NONCLUSTERED INDEX IX_SiteCollection_LockState   ON site.SiteCollection (LockState   ASC)

END